apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
  # nodeName: default
